"""fixing unique value

Revision ID: 3d9b01268b98
Revises: ed13f5431a32
Create Date: 2020-10-25 13:32:01.265237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9b01268b98'
down_revision = 'ed13f5431a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_city', table_name='clients')
    op.create_index(op.f('ix_clients_city'), 'clients', ['city'], unique=False)
    op.drop_index('ix_clients_postCode', table_name='clients')
    op.create_index(op.f('ix_clients_postCode'), 'clients', ['postCode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_postCode'), table_name='clients')
    op.create_index('ix_clients_postCode', 'clients', ['postCode'], unique=True)
    op.drop_index(op.f('ix_clients_city'), table_name='clients')
    op.create_index('ix_clients_city', 'clients', ['city'], unique=True)
    # ### end Alembic commands ###
