"""empty message

Revision ID: 4cd827f391a0
Revises: 3834011651e9
Create Date: 2020-10-21 14:10:27.721668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd827f391a0'
down_revision = '3834011651e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejf', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kls_ejf'), 'kls', ['ejf'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kls_ejf'), table_name='kls')
    op.drop_table('kls')
    # ### end Alembic commands ###
