"""empty message

Revision ID: 7e6d7b427985
Revises: 
Create Date: 2020-10-29 13:53:49.320128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6d7b427985'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('forename', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('homeAddress', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postCode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_clients_city'), 'clients', ['city'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_forename'), 'clients', ['forename'], unique=False)
    op.create_index(op.f('ix_clients_homeAddress'), 'clients', ['homeAddress'], unique=False)
    op.create_index(op.f('ix_clients_postCode'), 'clients', ['postCode'], unique=False)
    op.create_index(op.f('ix_clients_surname'), 'clients', ['surname'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_clients_surname'), table_name='clients')
    op.drop_index(op.f('ix_clients_postCode'), table_name='clients')
    op.drop_index(op.f('ix_clients_homeAddress'), table_name='clients')
    op.drop_index(op.f('ix_clients_forename'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_city'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
