"""Adding Languages

Revision ID: 941a32a4bef4
Revises: 3d9b01268b98
Create Date: 2020-10-25 19:55:25.087277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941a32a4bef4'
down_revision = '3d9b01268b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')
    # ### end Alembic commands ###
