"""adding contact tabel

Revision ID: a25e0ea61909
Revises: ce41ed62c814
Create Date: 2020-10-28 19:14:03.252449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25e0ea61909'
down_revision = 'ce41ed62c814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_clients_forename', table_name='clients')
    op.create_index(op.f('ix_clients_forename'), 'clients', ['forename'], unique=False)
    op.drop_index('ix_clients_homeAddress', table_name='clients')
    op.create_index(op.f('ix_clients_homeAddress'), 'clients', ['homeAddress'], unique=False)
    op.drop_index('ix_clients_surname', table_name='clients')
    op.create_index(op.f('ix_clients_surname'), 'clients', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_surname'), table_name='clients')
    op.create_index('ix_clients_surname', 'clients', ['surname'], unique=True)
    op.drop_index(op.f('ix_clients_homeAddress'), table_name='clients')
    op.create_index('ix_clients_homeAddress', 'clients', ['homeAddress'], unique=True)
    op.drop_index(op.f('ix_clients_forename'), table_name='clients')
    op.create_index('ix_clients_forename', 'clients', ['forename'], unique=True)
    op.drop_table('contacts')
    # ### end Alembic commands ###
