"""fixing name in lang

Revision ID: ce41ed62c814
Revises: 6dcb9eb04b12
Create Date: 2020-10-26 14:05:16.938266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce41ed62c814'
down_revision = '6dcb9eb04b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('languages_name_key', 'languages', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('languages_name_key', 'languages', ['name'])
    # ### end Alembic commands ###
