"""changing names for home and postcode

Revision ID: dd2c8e960665
Revises: 7e6d7b427985
Create Date: 2020-11-06 13:13:15.732280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2c8e960665'
down_revision = '7e6d7b427985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contacts')
    op.drop_table('languages')
    op.add_column('clients', sa.Column('home_address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('post_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_clients_home_address'), 'clients', ['home_address'], unique=False)
    op.create_index(op.f('ix_clients_post_code'), 'clients', ['post_code'], unique=False)
    op.drop_index('ix_clients_homeAddress', table_name='clients')
    op.drop_index('ix_clients_postCode', table_name='clients')
    op.drop_column('clients', 'homeAddress')
    op.drop_column('clients', 'postCode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('postCode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('homeAddress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_clients_postCode', 'clients', ['postCode'], unique=False)
    op.create_index('ix_clients_homeAddress', 'clients', ['homeAddress'], unique=False)
    op.drop_index(op.f('ix_clients_post_code'), table_name='clients')
    op.drop_index(op.f('ix_clients_home_address'), table_name='clients')
    op.drop_column('clients', 'post_code')
    op.drop_column('clients', 'home_address')
    op.create_table('languages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.uuid'], name='languages_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='languages_pkey')
    )
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.uuid'], name='contacts_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contacts_pkey')
    )
    op.drop_table('client_languages')
    op.drop_table('client_contacts')
    # ### end Alembic commands ###
