"""clientsss

Revision ID: ed13f5431a32
Revises: 4cd827f391a0
Create Date: 2020-10-22 14:13:42.105340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed13f5431a32'
down_revision = '4cd827f391a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('forename', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('homeAddress', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postCode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_clients_city'), 'clients', ['city'], unique=True)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_forename'), 'clients', ['forename'], unique=True)
    op.create_index(op.f('ix_clients_homeAddress'), 'clients', ['homeAddress'], unique=True)
    op.create_index(op.f('ix_clients_postCode'), 'clients', ['postCode'], unique=True)
    op.create_index(op.f('ix_clients_surname'), 'clients', ['surname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_surname'), table_name='clients')
    op.drop_index(op.f('ix_clients_postCode'), table_name='clients')
    op.drop_index(op.f('ix_clients_homeAddress'), table_name='clients')
    op.drop_index(op.f('ix_clients_forename'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_city'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
