"""Changing uuid to id in lang

Revision ID: f22a56c2e366
Revises: 941a32a4bef4
Create Date: 2020-10-25 20:21:30.913294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22a56c2e366'
down_revision = '941a32a4bef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('languages', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('languages', 'id')
    # ### end Alembic commands ###
